### ISSUE TITLE
ScrollablePositionedList: Unable to scroll inside Customscrollview

### ISSUE THREAD

**Issue by harasitCS** [google/flutter.widgets#86] opened 2020-04-10 15:22 UTC
scrollable_positioned_list not scrolling in following view hierarchy.

-----Customscrollview-----
   ---SliverToBoxAdapter---
    child: ScrollablePositionedList.builder

**Comment by jamesderlin** [comment] 2020-04-16 17:01
It would help a lot of if you could provide sample code that can reproduce the problem.  Thanks!

**Comment by jamesderlin** [comment] 2020-04-16 23:25
This is a duplicate of https://github.com/google/flutter.widgets/issues/32.

**Closed by jamesderlin** 2020-04-16 23:25 UTC
Labels: p: scrollable_positioned_list
