### ISSUE TITLE
VisibilityDetector no longer compiles

### ISSUE THREAD

**Issue by lifenautjoe** [google/flutter.widgets#21] opened 2019-09-05 10:39 UTC
When trying to include `VisibilityDetector`, any flutter command fails with

```
Running Gradle task 'assembleDevelopmentDebug'...

Compiler message:
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.5/lib/src/visibility_detector/src/visibility_detector_layer.dart:277:18: Error: This expression has type 'void' and can't be used.
    return super.addToScene(builder, layerOffset);
                 ^
```

This is due to a breaking change which hasn't been fixed here. 

https://github.com/flutter/flutter/pull/36402/files#diff-58600d3d2645a66835eb03f3c41b447bR848

**Comment by OsamaAbbas** [comment] 2019-09-05 10:42
I was about to open the same issue. How Strange! :)

**Comment by lifenautjoe** [comment] 2019-09-05 11:28
Welp, I've tried changing the code to the suggested on the broken change PR and just get an empty widget instead 😬

**Comment by lifenautjoe** [comment] 2019-09-05 11:55
Also forgot to add, this in the branch `dev`, works as expected on `stable`.

**Comment by jamesderlin** [comment] 2019-09-05 16:08
This is a duplicate of #20.  Let's move discussion there.

**Closed by jamesderlin** 2019-09-05 16:08 UTC
