### ISSUE TITLE
"The method 'readState' was called on null." when navigate between async  route page.

### ISSUE THREAD

**Issue by Zony-Zhao** [google/flutter.widgets#177] opened 2020-09-27 16:09 UTC
## Problem description
  scrollable_positioned_list: ^0.1.7

## Steps to reproduce

1. Create a simplest navigator example, where you can go back and forth.
2. In the route you are navigating to, use the scrollable_positioned_list example and wrapp it in a FutureBuilder( **I use  graphql_flutter: ^3.1.0 "Query" widget to wrap my ScrollablePositionedList, I think all async widget work the same** ).
3. (Not sure whether this has effect on this) I just used a "Hero" widget to wrap my navigate button in the first page, and another one with the same property "tag" to wrap my second page(whole page).

So it's like this 
### first page
- body
- hero
 - button
   - onTap navigate to second
### second page
- body
- hero
  - Query(future builder)
    - ScrollablePositionedList
## Expected behavior

no error!
## Actual behavior
get error when tapping the button to navigate.
```
The following NoSuchMethodError was thrown building Expanded(flex: 1):
The method 'readState' was called on null.
Receiver: null
Tried calling: readState(Instance of 'StatefulElement')

The relevant error-causing widget was:
  Expanded file:///E:/_project/flutter/upper_bunk_bro_frontend/lib/routes/DishList.dart:139:23

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _ScrollablePositionedListState.initState (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:232:60)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (7 frames)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#26     _invoke (dart:ui/hooks.dart:253:10)
#27     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
```
## Environment

Android emulator API30.

## Additional details

After taking a look at the stacktrace, I found that PageStorage.of(context).readState() is called in initState(), which does not make a null check. Not sure this is intended or not. And I didn't find a way to disable this behavior.

**Comment by jamesderlin** [comment] 2020-09-27 23:04
Duplicate of https://github.com/google/flutter.widgets/issues/110.

**Closed by jamesderlin** 2020-09-27 23:04 UTC
Labels: p: scrollable_positioned_list
