### ISSUE TITLE
Support shrinkwrap on scrollable_positioned_list

### ISSUE THREAD

**Issue by jgallow** [google/flutter.widgets#169] opened 2020-08-27 12:06 UTC
Regular ListViews support the [shrinkwrap](https://api.flutter.dev/flutter/widgets/ScrollView/shrinkWrap.html). Is is possible to add support for this?

**Comment by jamesderlin** [comment] 2020-09-18 00:32
Duplicate of https://github.com/google/flutter.widgets/issues/52.

**Closed by jamesderlin** 2020-09-18 00:32 UTC
Labels: duplicate, p: scrollable_positioned_list
