### ISSUE TITLE
ScrollTo/JumpTo Alignment

### ISSUE THREAD

**Issue by carekb684** [google/flutter.widgets#178] opened 2020-09-28 17:37 UTC
How is alignment supposed to work?
Say you have a horizontal scrollable list, and you use jumpTo with alignment= 0.
The item will end up at the start of the screen (left). If you want it to be at the Center of the screen i imagined alignment should be screenWidth / 2. But this does not work. To get the item to the center i arbitrarily set alignment = 0.365 (through trial and error) and this only works specifically for my phones screen width.

**Comment by tarobins** [comment] 2020-10-07 22:53
alignment = 0.5 should center the left edge of the item at the center.  Let me know if that's not  what you are looking for.

**Comment by gonzaaasanchez** [comment] 2020-10-23 21:24
> alignment = 0.5 should center the left edge of the item at the center of the list. Let me know if that's not what you are looking for.

Thanks for your reply!
I misunderstood that property, too. I thought it was like a padding. In my case I wanted a left 20px padding so I set alignment the (20 / viewWidth) value.

**Comment by marcglasberg** [comment] 2021-01-07 19:17
This issue is kind of a duplicate of: https://github.com/google/flutter.widgets/issues/99

**Comment by jamesderlin** [comment] 2021-01-21 22:25
This is a duplicate of https://github.com/google/flutter.widgets/issues/96.

**Closed by jamesderlin** 2021-01-21 22:25 UTC
Labels: SPL-docs, p: scrollable_positioned_list
