### ISSUE TITLE
Can't build app on Android or IOS after upgrading to flutter v2.8.0 

### ISSUE THREAD

**Issue by QasidLabeed** [google/flutter.widgets#314] opened 2021-12-15 12:58 UTC
After updating to flutter stable version 2.8.0.
Getting the following

Compiler message:
 1 warning generated.
  ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.0/lib/src/visibility_
    detector_layer.dart:276:21: Error: Too many positional arguments: 1 allowed, but 2 found.
    Try removing the extra positional arguments.
        super.addToScene(builder, layerOffset);

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.8.0 at /Users/qasidlabeed/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (7 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/qasidlabeed/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    ! Error: iPhone 11 Pro Max is not connected. Xcode will continue when iPhone 11 Pro Max is connected. (code -13)
```

**Comment by DKAC** [comment] 2021-12-16 11:50
+1

**Comment by selcukguvel** [comment] 2021-12-17 10:37
Using version `visibility_detector: 0.2.2` instead of `visibility_detector: 0.2.0` solved the issue for me.

**Comment by jamesderlin** [comment] 2021-12-17 10:38
This is a duplicate of #313.

**Comment by Nash0x7E2** [comment] 2021-12-30 01:22
There are still a few packages using the old version of visibility_detector causing errors at build times. Until these packages are upgraded, the following can be added to your `pubspec.yaml`:

```yaml
dependency_overrides:
  visibility_detector: ^0.2.2

```

**Comment by jamesderlin** [comment] 2022-01-29 20:04
@xster Can you close this please?

**Comment by xster** [comment] 2022-01-31 06:12
Thanks. Closing. And added you to maintainer.

**Closed by xster** 2022-01-31 06:12 UTC
